C=======================================================================
C
C=======================================================================
      SUBROUTINE BOCAC1(RTH,ID,NCVEL,ICVEL,NP,KOR,VREME,IND,NCVP,NCVPR,
     1                 CORD,NELCV)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CS.   PROGRAM
CS.      ZA STAMPANJE MERNE TABELE ZA TUNEL BOCAC ZA PROFIL 1; 92m
C .
C ......................................................................
C
      include 'paka.inc'
      
      COMMON /GRUPEE/ NGEL,NGENL,LGEOM,NGEOM,ITERM
      COMMON /ITERBR/ ITER
      COMMON /ECLANM/ AMAXK,AMINK,AMAXF,AMINF
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /OPSTIP/ JPS,JPBR,NPG,JIDG,JCORG,JCVEL,JELCV,NGA,NGI,NPK,
     1                NPUP,LIPODS,IPODS,LMAX13,MAX13,JEDNG,JMAXA,JEDNP,
     1                NWP,NWG,IDF,JPS1
      COMMON /ITERAC/ METOD,MAXIT,TOLE,TOLS,TOLM,KONVE,KONVS,KONVM
      COMMON /SRPSKI/ ISRPS
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
      COMMON /MAXREZ/ PMALL,BMALL,AMALL,SMKOR,SMALL,
     +                NPMALL,NBMALL,NAMALL,KPMALL,KBMALL,KAMALL,
     +                NSMKOR,NSMALL,NGRKOR,NGRALL,KSMALL
      COMMON /AUTSTP/ DTUK,ALFG,DELS,IAUTO,ITEOPT,KPNOD,KPDIR,KEQ
      COMMON /AUTST2/ PARAM(5)
      COMMON /AUTSTK/ DELUM,DELFM,KRAJP
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /MESLESS/ IGBM,ndif,idif(50),NKI,IKI(10)
      COMMON /MATIZO/ E,V
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CDEBUG/ IDEBUG
      COMMON /BOCACP1/ DP(19)
      DIMENSION RTH(*),ID(NP,*),NCVEL(*),NCVP(*),FSP(6),cord(np,*),
     1          NELCV(*),DL(19)
C
      IF(IDEBUG.GT.0) PRINT *, ' BOCAC'
C
C
      NA1=288349
      NB1=290741
      NC1=297048
      ND1=303317
      NE1=305034
c
      I90=90
      IF(KOR.EQ.1) THEN
         OPEN (I90,FILE='BOCPOM.POM',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
         WRITE(I90,*) '  METAR, NA1XYZ, NB1XYZ, NC1XYZ, ND1XYZ, NE1XYZ'
      ENDIF
      CALL NPOMER1(NA1,NB1,NC1,ND1,NE1,ICVEL,NELCV,ID,RTH,NP,I90,VREME)
C
      TPROF1=53.
      IF(VREME.LT.TPROF1) RETURN
      STAC=145.5001-VREME


C
      NBE111=263081
      NBE112=272672
      NBE113=279537
C
      NBE121=297147
      NBE122=297162
      NBE123=297372
C
      NBE131=338271
      NBE132=328920
      NBE133=314222
C
      KPROF=INT(VREME-TPROF1)
C     RACUNANJE POCETNIH DUZINA ZA KONVERGENCIJU
      II=99
      IF(KPROF.EQ.0) THEN
         OPEN (II,FILE='BOCAC1.POM',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
         WRITE(II,*) '    CELO, A1B1L0, A1C1L0, A1D1L0, A1E1L0,',
     1      ' B1C1L0, B1D1L0, D1C1L0,E1B1L0, E1C1L0, E1D1L0,   ',
     1      ' A111L0, A112L0, A113L0, C121L0, C122L0, C123L0,',
     1      ' E131L0, E132L0, E133L0'
         CALL MERKONV(NA1,NB1,DP(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NC1,DP(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,ND1,DP(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NE1,DP(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,NC1,DP(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,ND1,DP(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND1,NC1,DP(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NB1,DP(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NC1,DP(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,ND1,DP(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA1,NBE111,DP(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE112,DP(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE113,DP(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC1,NBE121,DP(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE122,DP(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE123,DP(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE1,NBE131,DP(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE132,DP(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE133,DP(19),ICVEL,NELCV,ID,RTH,CORD,NP)
c      WRITE(II,5000) (DP(I),I=1,19)
 5000 FORMAT(' DP0',10(1PE15.8))
      ENDIF
C
         CALL MERKONV(NA1,NB1,DL(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NC1,DL(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,ND1,DL(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NE1,DL(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,NC1,DL(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,ND1,DL(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND1,NC1,DL(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NB1,DL(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NC1,DL(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,ND1,DL(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA1,NBE111,DL(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE112,DL(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE113,DL(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC1,NBE121,DL(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE122,DL(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE123,DL(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE1,NBE131,DL(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE132,DL(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE133,DL(19),ICVEL,NELCV,ID,RTH,CORD,NP)

c      WRITE(II,5001) (DP(I),I=1,19)
 5001 FORMAT(' DP',10(1PE15.8))
c      WRITE(II,5002) (DL(I),I=1,19)
 5002 FORMAT(' DL',10(1PE15.8))
      DO 30 I=1,19
         DL(I)=(DL(I)-DP(I))*1000.
   30 CONTINUE
      WRITE(II,5100) STAC,(DL(I),I=1,19)
C
      RETURN
C
c 5100 FORMAT(' ',F9.3,10(1PE15.8))
 5100 FORMAT(' ',F9.3,10(F8.3),3x,9(F8.3))
C-----------------------------------------------------------------------
      END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE NPOMER1(NA1,NB1,NC1,ND1,NE1,ICVEL,NELCV,ID,RTH,NP,II,
     1                   VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      include 'paka.inc'
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
C
      DIMENSION RTH(*),ID(NP,*),NELCV(*),PA(3),PB(3),PC(3),PD(3),PE(3)
C
            IF(ICVEL.EQ.0) THEN
               NA=NA1
               NB=NB1
               NC=NC1
               ND=ND1
               NE=NE1
            ELSE
               NA=NELCV(NA1)
               NB=NELCV(NB1)
               NC=NELCV(NC1)
               ND=NELCV(ND1)
               NE=NELCV(NE1)
            ENDIF
         DO 10 J=1,3
            PA(J) = 0.D0
            KA=ID(NA,J)
            IF(KA.EQ.0) GO TO 10
            IF(KA.GT.0)THEN
               PA(J)=RTH(KA)
            ELSE
               PA(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KA)
            ENDIF
   10    CONTINUE
         DO 20 J=1,3
            PB(J) = 0.D0
            KB=ID(NB,J)
            IF(KB.EQ.0) GO TO 20
            IF(KB.GT.0)THEN
               PB(J)=RTH(KB)
            ELSE
               PB(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KB)
            ENDIF
   20    CONTINUE
         DO 30 J=1,3
            PC(J) = 0.D0
            KC=ID(NC,J)
            IF(KC.EQ.0) GO TO 30
            IF(KC.GT.0)THEN
               PC(J)=RTH(KC)
            ELSE
               PC(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KC)
            ENDIF
   30    CONTINUE
         DO 40 J=1,3
            PD(J) = 0.D0
            KD=ID(ND,J)
            IF(KD.EQ.0) GO TO 40
            IF(KD.GT.0)THEN
               PD(J)=RTH(KD)
            ELSE
               PD(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KD)
            ENDIF
   40    CONTINUE
         DO 50 J=1,3
            PE(J) = 0.D0
            KE=ID(NE,J)
            IF(KE.EQ.0) GO TO 50
            IF(KE.GT.0)THEN
               PE(J)=RTH(KE)
            ELSE
               PE(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KE)
            ENDIF
   50    CONTINUE
         DO 60 J=1,3
            PA(J)=PA(J)*1000
            PB(J)=PB(J)*1000
            PC(J)=PC(J)*1000
            PD(J)=PD(J)*1000
            PE(J)=PE(J)*1000
   60    CONTINUE
         METAR=INT(VREME)
      WRITE(II,5100) METAR,(PA(I),I=1,3),(PB(I),I=1,3),(PC(I),I=1,3),
     1                     (PD(I),I=1,3),(PE(I),I=1,3)
C
      RETURN
C
 5100 FORMAT(' ',I5,5(2X,3(F9.3)))
         RETURN
         END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE MERKONV(NA1,NB1,A1B1L0,ICVEL,NELCV,ID,RTH,CORD,NP)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      include 'paka.inc'
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
C
      DIMENSION RTH(*),ID(NP,*),cord(np,*),NELCV(*),PA(3),PB(3)
C
            IF(ICVEL.EQ.0) THEN
               NA=NA1
               NB=NB1
            ELSE
               NA=NELCV(NA1)
               NB=NELCV(NB1)
            ENDIF
         DO 10 J=1,3
            PA(J) = 0.D0
            KA=ID(NA,J)
            IF(KA.EQ.0) GO TO 10
            IF(KA.GT.0)THEN
               PA(J)=RTH(KA)
            ELSE
               PA(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KA)
            ENDIF
   10    CONTINUE
         DO 20 J=1,3
            PB(J) = 0.D0
            KB=ID(NB,J)
            IF(KB.EQ.0) GO TO 20
            IF(KB.GT.0)THEN
               PB(J)=RTH(KB)
            ELSE
               PB(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KB)
            ENDIF
   20    CONTINUE
            DX=CORD(NB,1)+PB(1)-CORD(NA,1)-PA(1)
            DY=CORD(NB,2)+PB(2)-CORD(NA,2)-PA(2)
            DZ=CORD(NB,3)+PB(3)-CORD(NA,3)-PA(3)
            A1B1L0=DSQRT(DX*DX+DY*DY+DZ*DZ)
         RETURN
         END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN1(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS1/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL1(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF1=53.
      IF(VREME.LT.TPROF1) RETURN
      STAC=145.5001-VREME
C
       NEL1(1)=449573
       NEL1(2)=449613
       NEL1(3)=449657
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL1(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF1)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL1(1)) II=91
      IF(NMM.EQ.NEL1(2)) II=92
      IF(NMM.EQ.NEL1(3)) II=93
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL1(1))
     1   OPEN (II,FILE='BOCAC1.P11',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL1(2))
     1   OPEN (II,FILE='BOCAC1.P12',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL1(3))
     1   OPEN (II,FILE='BOCAC1.P13',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL1(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL1(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL1(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL1(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL1(1).AND.JG.EQ.8).OR.
     1   (NMM.EQ.NEL1(2).AND.JG.EQ.8).OR.
     1   (NMM.EQ.NEL1(3).AND.JG.EQ.7))
     1WRITE(II,5105) STAC,NEL1(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
C=======================================================================
C=======================================================================
C=======================================================================
      SUBROUTINE BOCAC2(RTH,ID,NCVEL,ICVEL,NP,KOR,VREME,IND,NCVP,NCVPR,
     1                 CORD,NELCV)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CS.   PROGRAM
CS.      ZA STAMPANJE MERNE TABELE ZA TUNEL BOCAC ZA PROFIL 2; 80m
C .
C ......................................................................
C
      include 'paka.inc'
      
      COMMON /GRUPEE/ NGEL,NGENL,LGEOM,NGEOM,ITERM
      COMMON /ITERBR/ ITER
      COMMON /ECLANM/ AMAXK,AMINK,AMAXF,AMINF
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /OPSTIP/ JPS,JPBR,NPG,JIDG,JCORG,JCVEL,JELCV,NGA,NGI,NPK,
     1                NPUP,LIPODS,IPODS,LMAX13,MAX13,JEDNG,JMAXA,JEDNP,
     1                NWP,NWG,IDF,JPS1
      COMMON /ITERAC/ METOD,MAXIT,TOLE,TOLS,TOLM,KONVE,KONVS,KONVM
      COMMON /SRPSKI/ ISRPS
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
      COMMON /MAXREZ/ PMALL,BMALL,AMALL,SMKOR,SMALL,
     +                NPMALL,NBMALL,NAMALL,KPMALL,KBMALL,KAMALL,
     +                NSMKOR,NSMALL,NGRKOR,NGRALL,KSMALL
      COMMON /AUTSTP/ DTUK,ALFG,DELS,IAUTO,ITEOPT,KPNOD,KPDIR,KEQ
      COMMON /AUTST2/ PARAM(5)
      COMMON /AUTSTK/ DELUM,DELFM,KRAJP
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /MESLESS/ IGBM,ndif,idif(50),NKI,IKI(10)
      COMMON /MATIZO/ E,V
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CDEBUG/ IDEBUG
      COMMON /BOCACP2/ DP(19)
      DIMENSION RTH(*),ID(NP,*),NCVEL(*),NCVP(*),FSP(6),cord(np,*),
     1          NELCV(*),DL(19)
C
      IF(IDEBUG.GT.0) PRINT *, ' BOCAC'
C
      TPROF2=67.
      IF(VREME.LT.TPROF2) RETURN
      STAC=146.5001-VREME
C
      NA2=253877
      NB2=255123
      NC2=257684
      ND2=260355
      NE2=261191


C
      NBE211=234105
      NBE212=243273
      NBE213=249999
C
      NBE221=258061
      NBE222=258090
      NBE223=258132
C
      NBE231=276910
      NBE232=269994
      NBE233=265225
C
      KPROF=INT(VREME-TPROF2)
C     RACUNANJE POCETNIH DUZINA ZA KONVERGENCIJU
      II=98
      IF(KPROF.EQ.0) THEN
         OPEN (II,FILE='BOCAC2.POM',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
         WRITE(II,*) '    CELO, A2B2L0, A2C2L0, A2D2L0, A2E2L0,',
     1      ' B2C2L0, B2D2L0, D2C2L0,E2B2L0, E2C2L0, E2D2L0,   ',
     1      ' A211L0, A212L0, A213L0, C221L0, C222L0, C223L0,',
     1      ' E231L0, E232L0, E233L0'
         CALL MERKONV(NA2,NB2,DP(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NC2,DP(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,ND2,DP(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NE2,DP(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,NC2,DP(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,ND2,DP(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND2,NC2,DP(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NB2,DP(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NC2,DP(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,ND2,DP(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA2,NBE211,DP(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE212,DP(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE213,DP(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC2,NBE221,DP(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE222,DP(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE223,DP(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE2,NBE231,DP(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE232,DP(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE233,DP(19),ICVEL,NELCV,ID,RTH,CORD,NP)
c      WRITE(II,5000) (DP(I),I=1,19)
 5000 FORMAT(' DP0',10(1PE15.8))
      ENDIF
C
         CALL MERKONV(NA2,NB2,DL(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NC2,DL(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,ND2,DL(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NE2,DL(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,NC2,DL(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,ND2,DL(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND2,NC2,DL(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NB2,DL(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NC2,DL(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,ND2,DL(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA2,NBE211,DL(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE212,DL(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE213,DL(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC2,NBE221,DL(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE222,DL(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE223,DL(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE2,NBE231,DL(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE232,DL(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE233,DL(19),ICVEL,NELCV,ID,RTH,CORD,NP)

c      WRITE(II,5001) (DP(I),I=1,19)
 5001 FORMAT(' DP',10(1PE15.8))
c      WRITE(II,5002) (DL(I),I=1,19)
 5002 FORMAT(' DL',10(1PE15.8))
      DO 30 I=1,19
         DL(I)=(DL(I)-DP(I))*1000.
   30 CONTINUE
      WRITE(II,5100) STAC,(DL(I),I=1,19)
C
      RETURN
C
c 5100 FORMAT(' ',F9.3,10(1PE15.8))
 5100 FORMAT(' ',F9.3,10(F8.3),3x,9(F8.3))
C-----------------------------------------------------------------------
      END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN2(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS2/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL2(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF2=67.
      IF(VREME.LT.TPROF2) RETURN
      STAC=146.5001-VREME
C
       NEL2(1)=446963
       NEL2(2)=446973
       NEL2(3)=446984
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL2(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF2)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL2(1)) II=94
      IF(NMM.EQ.NEL2(2)) II=95
      IF(NMM.EQ.NEL2(3)) II=96
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL2(1))
     1   OPEN (II,FILE='BOCAC2.P21',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL2(2))
     1   OPEN (II,FILE='BOCAC2.P22',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL2(3))
     1   OPEN (II,FILE='BOCAC2.P23',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL2(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL2(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL2(1).AND.JG.EQ.2).OR.
     1   (NMM.EQ.NEL2(2).AND.JG.EQ.2).OR.
     1   (NMM.EQ.NEL2(3).AND.JG.EQ.4))
     1WRITE(II,5105) STAC,NEL2(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
C=======================================================================
C=======================================================================
      SUBROUTINE BOCAC3(RTH,ID,NCVEL,ICVEL,NP,KOR,VREME,IND,NCVP,NCVPR,
     1                 CORD,NELCV)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CS.   PROGRAM
CS.      ZA STAMPANJE MERNE TABELE ZA TUNEL BOCAC ZA PROFIL 2; 80m
C .
C ......................................................................
C
      include 'paka.inc'
      
      COMMON /GRUPEE/ NGEL,NGENL,LGEOM,NGEOM,ITERM
      COMMON /ITERBR/ ITER
      COMMON /ECLANM/ AMAXK,AMINK,AMAXF,AMINF
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /OPSTIP/ JPS,JPBR,NPG,JIDG,JCORG,JCVEL,JELCV,NGA,NGI,NPK,
     1                NPUP,LIPODS,IPODS,LMAX13,MAX13,JEDNG,JMAXA,JEDNP,
     1                NWP,NWG,IDF,JPS1
      COMMON /ITERAC/ METOD,MAXIT,TOLE,TOLS,TOLM,KONVE,KONVS,KONVM
      COMMON /SRPSKI/ ISRPS
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
      COMMON /MAXREZ/ PMALL,BMALL,AMALL,SMKOR,SMALL,
     +                NPMALL,NBMALL,NAMALL,KPMALL,KBMALL,KAMALL,
     +                NSMKOR,NSMALL,NGRKOR,NGRALL,KSMALL
      COMMON /AUTSTP/ DTUK,ALFG,DELS,IAUTO,ITEOPT,KPNOD,KPDIR,KEQ
      COMMON /AUTST2/ PARAM(5)
      COMMON /AUTSTK/ DELUM,DELFM,KRAJP
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /MESLESS/ IGBM,ndif,idif(50),NKI,IKI(10)
      COMMON /MATIZO/ E,V
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CDEBUG/ IDEBUG
      COMMON /BOCACP3/ DP(19)
      DIMENSION RTH(*),ID(NP,*),NCVEL(*),NCVP(*),FSP(6),cord(np,*),
     1          NELCV(*),DL(19)
C
      IF(IDEBUG.GT.0) PRINT *, ' BOCAC'
C
      TPROF2=82.
      IF(VREME.LT.TPROF2) RETURN
      STAC=147.5001-VREME
C
      NA2=212596
      NB2=213096
      NC2=213945
      ND2=214720
      NE2=214962


C
      NBE211=198777
      NBE212=203150
      NBE213=211167
C
      NBE221=214061
      NBE222=214058
      NBE223=214231
C
      NBE231=222845
      NBE232=219067
      NBE233=216263
C
      KPROF=INT(VREME-TPROF2)
C     RACUNANJE POCETNIH DUZINA ZA KONVERGENCIJU
      II=97
      IF(KPROF.EQ.0) THEN
         OPEN (II,FILE='BOCAC3.POM',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
         WRITE(II,*) '    CELO, A3B3L0, A3C3L0, A3D3L0, A3E3L0,',
     1      ' B3C3L0, B3D230, D3C3L0,E3B3L0, E3C3L0, E3D3L0,   ',
     1      ' A311L0, A312L0, A313L0, C321L0, C322L0, C323L0,',
     1      ' E331L0, E332L0, E333L0'
         CALL MERKONV(NA2,NB2,DP(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NC2,DP(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,ND2,DP(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NE2,DP(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,NC2,DP(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,ND2,DP(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND2,NC2,DP(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NB2,DP(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NC2,DP(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,ND2,DP(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA2,NBE211,DP(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE212,DP(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE213,DP(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC2,NBE221,DP(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE222,DP(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE223,DP(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE2,NBE231,DP(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE232,DP(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE233,DP(19),ICVEL,NELCV,ID,RTH,CORD,NP)
c      WRITE(II,5000) (DP(I),I=1,19)
 5000 FORMAT(' DP0',10(1PE15.8))
      ENDIF
C
         CALL MERKONV(NA2,NB2,DL(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NC2,DL(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,ND2,DL(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NE2,DL(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,NC2,DL(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,ND2,DL(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND2,NC2,DL(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NB2,DL(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NC2,DL(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,ND2,DL(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA2,NBE211,DL(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE212,DL(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE213,DL(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC2,NBE221,DL(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE222,DL(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE223,DL(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE2,NBE231,DL(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE232,DL(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE233,DL(19),ICVEL,NELCV,ID,RTH,CORD,NP)

c      WRITE(II,5001) (DP(I),I=1,19)
 5001 FORMAT(' DP',10(1PE15.8))
c      WRITE(II,5002) (DL(I),I=1,19)
 5002 FORMAT(' DL',10(1PE15.8))
      DO 30 I=1,19
         DL(I)=(DL(I)-DP(I))*1000.
   30 CONTINUE
      WRITE(II,5100) STAC,(DL(I),I=1,19)
C
      RETURN
C
c 5100 FORMAT(' ',F9.3,10(1PE15.8))
 5100 FORMAT(' ',F9.3,10(F8.3),3x,9(F8.3))
C-----------------------------------------------------------------------
      END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN3(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS3/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL2(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF2=82.
      IF(VREME.LT.TPROF2) RETURN
      STAC=147.5001-VREME
C
       NEL2(1)=444168
       NEL2(2)=444158
       NEL2(3)=444147
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL2(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF2)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL2(1)) II=84
      IF(NMM.EQ.NEL2(2)) II=85
      IF(NMM.EQ.NEL2(3)) II=86
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL2(1))
     1   OPEN (II,FILE='BOCAC3.P31',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL2(2))
     1   OPEN (II,FILE='BOCAC3.P32',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL2(3))
     1   OPEN (II,FILE='BOCAC3.P33',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL2(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL2(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL2(1).AND.JG.EQ.4).OR.
     1   (NMM.EQ.NEL2(2).AND.JG.EQ.4).OR.
     1   (NMM.EQ.NEL2(3).AND.JG.EQ.8))
     1WRITE(II,5105) STAC,NEL2(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
	  