C=======================================================================
C
C=======================================================================
      SUBROUTINE BOCAC(RTH,ID,NCVEL,ICVEL,NP,KOR,VREME,IND,NCVP,NCVPR,
     1                 CORD,NELCV)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CS.   PROGRAM
CS.      ZA STAMPANJE MERNE TABELE ZA TUNEL BOCAC ZA PROFIL 1; 92m
C .
C ......................................................................
C
      include 'paka.inc'
      
      COMMON /GRUPEE/ NGEL,NGENL,LGEOM,NGEOM,ITERM
      COMMON /ITERBR/ ITER
      COMMON /ECLANM/ AMAXK,AMINK,AMAXF,AMINF
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /OPSTIP/ JPS,JPBR,NPG,JIDG,JCORG,JCVEL,JELCV,NGA,NGI,NPK,
     1                NPUP,LIPODS,IPODS,LMAX13,MAX13,JEDNG,JMAXA,JEDNP,
     1                NWP,NWG,IDF,JPS1
      COMMON /ITERAC/ METOD,MAXIT,TOLE,TOLS,TOLM,KONVE,KONVS,KONVM
      COMMON /SRPSKI/ ISRPS
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
      COMMON /MAXREZ/ PMALL,BMALL,AMALL,SMKOR,SMALL,
     +                NPMALL,NBMALL,NAMALL,KPMALL,KBMALL,KAMALL,
     +                NSMKOR,NSMALL,NGRKOR,NGRALL,KSMALL
      COMMON /AUTSTP/ DTUK,ALFG,DELS,IAUTO,ITEOPT,KPNOD,KPDIR,KEQ
      COMMON /AUTST2/ PARAM(5)
      COMMON /AUTSTK/ DELUM,DELFM,KRAJP
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /MESLESS/ IGBM,ndif,idif(50),NKI,IKI(10)
      COMMON /MATIZO/ E,V
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CDEBUG/ IDEBUG
      COMMON /BOCACP/ DP(19)
      DIMENSION RTH(*),ID(NP,*),NCVEL(*),NCVP(*),FSP(6),cord(np,*),
     1          NELCV(*),DL(19)
C
      IF(IDEBUG.GT.0) PRINT *, ' BOCAC'
C
      TPROF1=54.
      IF(VREME.LT.TPROF1) RETURN
C
      NA1=286019
      NB1=288297
      NC1=294335
      ND1=300307
      NE1=301966


C
      NBE111=277590
      NBE112=270834
      NBE113=261281
C
      NBE121=294421
      NBE122=294441
      NBE123=294661
C
      NBE131=324757
      NBE132=317139
      NBE133=310878
C
      KPROF=INT(VREME-TPROF1)
C     RACUNANJE POCETNIH DUZINA ZA KONVERGENCIJU
      II=99
      IF(KPROF.EQ.0) THEN
         OPEN (II,FILE='BOCAC.REZ',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
         WRITE(II,*) '     CELO, A1B1L0, A1C1L0, A1D1L0, A1E1L0,',
     1       ' B1C1L0, B1D1L0, D1C1L0,E1B1L0, E1C1L0, E1D1L0,   ',
     1       ' A111L0, A112L0, A113L0, C121L0, C122L0, C123L0,',
     1       ' E131L0, E132L0, E133L0'
         CALL MERKONV(NA1,NB1,DP(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NC1,DP(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,ND1,DP(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,NC1,DP(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,ND1,DP(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND1,NC1,DP(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NB1,DP(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NC1,DP(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,ND1,DP(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NE1,DP(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA1,NBE111,DP(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE112,DP(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE113,DP(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC1,NBE121,DP(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE122,DP(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE123,DP(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE1,NBE131,DP(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE132,DP(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE133,DP(19),ICVEL,NELCV,ID,RTH,CORD,NP)
c      WRITE(II,5000) (DP(I),I=1,19)
 5000 FORMAT(' DP0',10(1PE15.8))
      ENDIF
C
         CALL MERKONV(NA1,NB1,DL(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NC1,DL(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,ND1,DL(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,NC1,DL(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,ND1,DL(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND1,NC1,DL(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NB1,DL(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NC1,DL(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,ND1,DL(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NE1,DL(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA1,NBE111,DL(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE112,DL(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE113,DL(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC1,NBE121,DL(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE122,DL(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE123,DL(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE1,NBE131,DL(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE132,DL(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE133,DL(19),ICVEL,NELCV,ID,RTH,CORD,NP)

c      WRITE(II,5001) (DP(I),I=1,19)
 5001 FORMAT(' DP',10(1PE15.8))
c      WRITE(II,5002) (DL(I),I=1,19)
 5002 FORMAT(' DL',10(1PE15.8))
      DO 30 I=1,19
         DL(I)=(DL(I)-DP(I))*1000.
   30 CONTINUE
      STAC=146.5001-VREME
      WRITE(II,5100) STAC,(DL(I),I=1,19)
C
      RETURN
C
c 5100 FORMAT(' ',F9.3,10(1PE15.8))
 5100 FORMAT(' ',F9.3,10(F8.3),3x,9(F8.3))
C-----------------------------------------------------------------------
      END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE MERKONV(NA1,NB1,A1B1L0,ICVEL,NELCV,ID,RTH,CORD,NP)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      include 'paka.inc'
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
C
      DIMENSION RTH(*),ID(NP,*),cord(np,*),NELCV(*),PA(3),PB(3)
C
            IF(ICVEL.EQ.0) THEN
               NA=NA1
               NB=NB1
            ELSE
               NA=NELCV(NA1)
               NB=NELCV(NB1)
            ENDIF
         DO 10 J=1,3
            PA(J) = 0.D0
            KA=ID(NA,J)
            IF(KA.EQ.0) GO TO 10
            IF(KA.GT.0)THEN
               PA(J)=RTH(KA)
            ELSE
               PA(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KA)
            ENDIF
   10    CONTINUE
         DO 20 J=1,3
            PB(J) = 0.D0
            KB=ID(NB,J)
            IF(KB.EQ.0) GO TO 20
            IF(KB.GT.0)THEN
               PB(J)=RTH(KB)
            ELSE
               PB(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KB)
            ENDIF
   20    CONTINUE
            DX=CORD(NB,1)+PB(1)-CORD(NA,1)-PA(1)
            DY=CORD(NB,2)+PB(2)-CORD(NA,2)-PA(2)
            DZ=CORD(NB,3)+PB(3)-CORD(NA,3)-PA(3)
            A1B1L0=DSQRT(DX*DX+DY*DY+DZ*DZ)
         RETURN
         END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL1(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF1=55.
      IF(VREME.LT.TPROF1) RETURN
      STAC=147.5001-VREME
C
       NEL1(1)=449189
       NEL1(2)=449229
       NEL1(3)=449273
c       NEL1(4)=291742
c       NEL1(5)=291682
c       NEL1(6)=291616
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL1(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF1)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL1(1)) II=91
      IF(NMM.EQ.NEL1(2)) II=92
      IF(NMM.EQ.NEL1(3)) II=93
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL1(1))
     1   OPEN (II,FILE='BOCAC.189',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL1(2))
     1   OPEN (II,FILE='BOCAC.229',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL1(3))
     1   OPEN (II,FILE='BOCAC.273',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL1(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL1(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL1(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL1(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL1(1).AND.JG.EQ.8).OR.
     1   (NMM.EQ.NEL1(2).AND.JG.EQ.7).OR.
     1   (NMM.EQ.NEL1(3).AND.JG.EQ.8))
     1WRITE(II,5105) STAC,NEL1(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
